development:
  adapter: postgresql
  encoding: unicode
  database: where_am_i_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: where_am_i_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: where_am_i_production
  pool: 5
